# Generated by Django 5.2.12 on 2026-03-29 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='英文名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文献分类',
                'verbose_name_plural': '文献分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(blank=True, max_length=20, unique=True, verbose_name='PMID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='关键词')),
                ('authors', models.TextField(blank=True, verbose_name='作者')),
                ('journal', models.CharField(blank=True, max_length=200, verbose_name='期刊')),
                ('publish_year', models.IntegerField(blank=True, null=True, verbose_name='发表年份')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('language', models.CharField(default='zh', max_length=20, verbose_name='语言')),
                ('text_vector', models.TextField(blank=True, verbose_name='文本向量')),
                ('text_length', models.IntegerField(default=0, verbose_name='文本长度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literatures', to='literature.literaturecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '医学文献',
                'verbose_name_plural': '医学文献',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('accuracy', models.FloatField(verbose_name='准确率')),
                ('precision', models.FloatField(verbose_name='精确率')),
                ('recall', models.FloatField(verbose_name='召回率')),
                ('f1_score', models.FloatField(verbose_name='F1值')),
                ('support', models.IntegerField(verbose_name='样本数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='literature.literaturecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '模型评估',
                'verbose_name_plural': '模型评估',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='搜索词')),
                ('search_type', models.CharField(choices=[('keyword', '关键词搜索'), ('semantic', '语义搜索'), ('category', '分类搜索')], max_length=20, verbose_name='搜索类型')),
                ('results_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搜索历史',
                'verbose_name_plural': '搜索历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0, verbose_name='相似度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('similar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='literature.literature', verbose_name='相似文献')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='literature.literature', verbose_name='源文献')),
            ],
            options={
                'verbose_name': '相似文献',
                'verbose_name_plural': '相似文献',
                'unique_together': {('source', 'similar')},
            },
        ),
    ]
